---
- name: Install node exporter
  apt:
    name: prometheus-node-exporter
    state: present
    update_cache: true

- name: Enable node exporter
  systemd:
    name: prometheus-node-exporter
    enabled: true
    state: started